services:

  worker:
    container_name: worker-celery5
    hostname: worker
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: example/celery5/Dockerfile
    command: ["celery", "-A", "tasks", "worker", "-l", "INFO"]
    depends_on:
      - redis
    stdin_open: true
    tty: true

  beat:
    container_name: beat-celery5
    hostname: beat
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: example/celery5/Dockerfile
    command:
      ["celery", "-A", "tasks", "beat", "-S", "redisbeat.RedisScheduler", "-l", "INFO"]
    depends_on:
      - worker
      - redis
    stdin_open: true
    tty: true

  redis:
    container_name: redis-celery5
    hostname: redis
    restart: unless-stopped
    image: redis
