#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright 2017-2020 Liqiang Lau
"""
 @desc: `
 @author: liqiang liu
 @contact: liqiangliu443@gmail.com
 @site: https://liqiang.io
 @created at: 2020/3/7
"""

DEFUALT_INIT_POLICY = "DEFAULT"
INIT_POLICY_RESET = "RESET"
INIT_POLICY_IMMEDIATELY = "IMMEDIATELY"
INIT_POLICY_FAST_FORWARD = "FAST_FORWARD"

INIT_POLICIES = [
    INIT_POLICY_RESET,
    DEFUALT_INIT_POLICY,
    INIT_POLICY_IMMEDIATELY,
    INIT_POLICY_FAST_FORWARD,
]

CONFIG_INIT_POLICY = "CELERY_REDIS_SCHEDULER_INIT_POLICY"
BROKER_URL = "CELERY_REDIS_SCHEDULER_URL"
BROKER_TRANSPORT_OPTIONS = "CELERY_BROKER_TRANSPORT_OPTIONS"
BROKER_KEY = "CELERY_REDIS_SCHEDULER_KEY"
MULTI_NODE_MODE = "CELERY_REDIS_MULTI_NODE_MODE"
LOCK_TTL = "CELERY_REDIS_SCHEDULER_LOCK_TTL"